# ./docker-compose.yml
version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'   
      MYSQL_USER: 'dbadmin'
      MYSQL_PASSWORD: 'somepass'      
      MYSQL_ROOT_PASSWORD: 'somerootpass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
	  

  web:
    image: php:latest
    container_name: php_web
    depends_on:
      - database
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
